name: Upgrade Unit Test
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*
  workflow_dispatch: {}
permissions:
  contents: read
env:
  GO_VERSION: '1.23.8'
jobs:
  upgrade-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k8s-version: ['v1.29.8']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.k8s-version }}
      cancel-in-progress: true
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make \
            gcc \
            jq \
            ca-certificates \
            curl \
            gnupg
          sudo snap install kubectl --classic
          sudo snap install helm --classic
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Setup KinD with Kubernetes ${{ matrix.k8s-version }}
        run: |
          go install sigs.k8s.io/kind@v0.24.0
          kind delete cluster || true
          kind create cluster --image=kindest/node:${{ matrix.k8s-version }} --wait=60s
      - name: Get latest KubeVela release tag (no v prefix)
        id: get_latest_tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/kubevela/kubevela/releases/latest | \
                jq -r ".tag_name" | \
                awk '{sub(/^v/, ""); print}')
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
      - name: Get Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.14.0
      - name: Build vela CLI
        run: make vela-cli
      - name: Build kubectl-vela plugin
        run: make kubectl-vela
      - name: Install kustomize
        run: make kustomize
      - name: Add KubeVela Helm repo
        run: |
          helm repo add kubevela https://kubevela.github.io/charts
          helm repo update
      - name: Install KubeVela ${{ env.LATEST_TAG }}
        run: |
          helm install --create-namespace -n vela-system kubevela kubevela/vela-core \
            --version ${{ env.LATEST_TAG }} \
            --timeout 10m \
            --wait
      - name: Post-install status
        run: |
          kubectl get pods -n vela-system
          kubectl rollout status deployment/kubevela-vela-core -n vela-system --timeout=300s
          kubectl get crd applications.core.oam.dev
      - name: Check vela version
        run: ./bin/vela version
      - name: Get commit hash
        id: commit_hash
        run: |
          echo "COMMIT_HASH=git-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and load Docker image
        run: |
          mkdir -p $HOME/tmp/
          # Build test image with coverage instrumentation for testing workflow
          docker build -t vela-core-test:${{ env.COMMIT_HASH }} -f Dockerfile .
          # Load image into KinD cluster
          TMPDIR=$HOME/tmp/ kind load docker-image vela-core-test:${{ env.COMMIT_HASH }}
      - name: Upgrade KubeVela to local image
        run: |
          helm upgrade kubevela ./charts/vela-core \
            --namespace vela-system \
            --set image.repository=vela-core-test \
            --set image.tag=${{ env.COMMIT_HASH }} \
            --set image.pullPolicy=IfNotPresent \
            --timeout 5m \
            --wait \
            --debug
      - name: Post-upgrade status
        run: |
          echo "Verifying upgrade to local development image..."
          kubectl get pods -n vela-system
          kubectl rollout status deployment/kubevela-vela-core -n vela-system --timeout=300s
          echo "Checking deployed image version..."
          kubectl get deployment kubevela-vela-core -n vela-system -o yaml | grep "image:" | head -1
      - name: Run unit tests
        run: make test
